// Date: 18/05/2014 10:20:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package robomuss.rc.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSlopedTrack extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Top_1;
    ModelRenderer Top_2;
  
  public ModelSlopedTrack()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-8F, 0F, -2F, 26, 3, 4);
      Base.setRotationPoint(-1F, 14F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0.7853982F);
      Top_1 = new ModelRenderer(this, 0, 0);
      Top_1.addBox(-8F, 0F, -1F, 26, 2, 3);
      Top_1.setRotationPoint(0F, 12.5F, -5.5F);
      Top_1.setTextureSize(64, 32);
      Top_1.mirror = true;
      setRotation(Top_1, 0F, 0F, 0.7853982F);
      Top_2 = new ModelRenderer(this, 0, 0);
      Top_2.addBox(-8F, 0F, -1F, 26, 2, 3);
      Top_2.setRotationPoint(0F, 12.5F, 4.5F);
      Top_2.setTextureSize(64, 32);
      Top_2.mirror = true;
      setRotation(Top_2, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Top_1.render(f5);
    Top_2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
