// Date: 18/05/2014 11:55:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package robomuss.rc.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransitionTrack2 extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Top_1;
    ModelRenderer Top_2;
    ModelRenderer Shape1;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape2;
    ModelRenderer Shape6;
  
  public ModelTransitionTrack2()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-8F, 0F, -2F, 26, 3, 4);
      Base.setRotationPoint(-1F, 14F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0.7853982F);
      Top_1 = new ModelRenderer(this, 0, 0);
      Top_1.addBox(-8F, 0F, -1F, 26, 2, 3);
      Top_1.setRotationPoint(0F, 12.5F, -5.5F);
      Top_1.setTextureSize(64, 32);
      Top_1.mirror = true;
      setRotation(Top_1, 0F, 0F, 0.7853982F);
      Top_2 = new ModelRenderer(this, 0, 0);
      Top_2.addBox(-8F, 0F, -1F, 26, 2, 3);
      Top_2.setRotationPoint(0F, 12.5F, 4.5F);
      Top_2.setTextureSize(64, 32);
      Top_2.mirror = true;
      setRotation(Top_2, 0F, 0F, 0.7853982F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 5, 3, 4);
      Shape1.setRotationPoint(-12F, 5F, -2F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 9, 3, 4);
      Shape3.setRotationPoint(-7F, 5F, -2F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 1.047198F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 11, 2, 3);
      Shape4.setRotationPoint(-7F, 2F, 3.5F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 1.047198F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 13, 2, 3);
      Shape5.setRotationPoint(-7F, 2F, -6.5F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 1.047198F);
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 6, 2, 3);
      Shape2.setRotationPoint(-13F, 1.5F, 3.5F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 0);
      Shape6.addBox(0F, 0F, 0F, 6, 2, 3);
      Shape6.setRotationPoint(-13F, 1.5F, -6.5F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Top_1.render(f5);
    Top_2.render(f5);
    Shape1.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape2.render(f5);
    Shape6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
