// Date: 18/05/2014 11:15:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package robomuss.rc.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransitionTrack extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Top_1;
    ModelRenderer Top_2;
    ModelRenderer Base_1;
    ModelRenderer Base_2;
    ModelRenderer Base_3;
    ModelRenderer Base_4;
    ModelRenderer Base_5;
    ModelRenderer Base_6;
    ModelRenderer Base_7;
    ModelRenderer Base_8;
    ModelRenderer Base_11;
    ModelRenderer Base_12;
  
  public ModelTransitionTrack()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-8F, 0F, -2F, 8, 3, 4);
      Base.setRotationPoint(-1F, 14F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0.7853982F);
      Top_1 = new ModelRenderer(this, 0, 0);
      Top_1.addBox(-8F, 0F, -1F, 8, 2, 3);
      Top_1.setRotationPoint(0F, 12.5F, -5.5F);
      Top_1.setTextureSize(64, 32);
      Top_1.mirror = true;
      setRotation(Top_1, 0F, 0F, 0.7853982F);
      Top_2 = new ModelRenderer(this, 0, 0);
      Top_2.addBox(-8F, 0F, -1F, 8, 2, 3);
      Top_2.setRotationPoint(0F, 12.5F, 4.5F);
      Top_2.setTextureSize(64, 32);
      Top_2.mirror = true;
      setRotation(Top_2, 0F, 0F, 0.7853982F);
      Base_1 = new ModelRenderer(this, 0, 0);
      Base_1.addBox(0F, 0F, 0F, 4, 3, 4);
      Base_1.setRotationPoint(-1F, 14F, -2F);
      Base_1.setTextureSize(64, 32);
      Base_1.mirror = true;
      setRotation(Base_1, 0F, 0F, 1.047198F);
      Base_2 = new ModelRenderer(this, 0, 0);
      Base_2.addBox(0F, 0F, 0F, 4, 3, 4);
      Base_2.setRotationPoint(4F, 21F, -2F);
      Base_2.setTextureSize(64, 32);
      Base_2.mirror = true;
      setRotation(Base_2, 0F, 0F, 0F);
      Base_3 = new ModelRenderer(this, 0, 0);
      Base_3.addBox(0F, 0F, 0F, 4, 3, 4);
      Base_3.setRotationPoint(2F, 19F, -2F);
      Base_3.setTextureSize(64, 32);
      Base_3.mirror = true;
      setRotation(Base_3, 0F, 0F, 0.5235988F);
      Base_4 = new ModelRenderer(this, 0, 0);
      Base_4.addBox(0F, 0F, 0F, 5, 3, 4);
      Base_4.setRotationPoint(0F, 16F, -2F);
      Base_4.setTextureSize(64, 32);
      Base_4.mirror = true;
      setRotation(Base_4, 0F, 0F, 0.9599311F);
      Base_5 = new ModelRenderer(this, 0, 0);
      Base_5.addBox(0F, 0F, 0F, 4, 2, 3);
      Base_5.setRotationPoint(0F, 12.5F, -6.5F);
      Base_5.setTextureSize(64, 32);
      Base_5.mirror = true;
      setRotation(Base_5, 0F, 0F, 1.047198F);
      Base_6 = new ModelRenderer(this, 0, 0);
      Base_6.addBox(0F, 0F, 0F, 4, 2, 3);
      Base_6.setRotationPoint(0F, 12.5F, 3.5F);
      Base_6.setTextureSize(64, 32);
      Base_6.mirror = true;
      setRotation(Base_6, 0F, 0F, 1.047198F);
      Base_7 = new ModelRenderer(this, 0, 0);
      Base_7.addBox(0F, 0F, 0F, 5, 2, 3);
      Base_7.setRotationPoint(1F, 14.5F, -6.5F);
      Base_7.setTextureSize(64, 32);
      Base_7.mirror = true;
      setRotation(Base_7, 0F, 0F, 0.9599311F);
      Base_8 = new ModelRenderer(this, 0, 0);
      Base_8.addBox(0F, 0F, 0F, 5, 2, 3);
      Base_8.setRotationPoint(1F, 14.5F, 3.5F);
      Base_8.setTextureSize(64, 32);
      Base_8.mirror = true;
      setRotation(Base_8, 0F, 0F, 0.9599311F);
      Base_11 = new ModelRenderer(this, 0, 0);
      Base_11.addBox(0F, 0F, 0F, 6, 2, 3);
      Base_11.setRotationPoint(2F, 17.5F, 3.5F);
      Base_11.setTextureSize(64, 32);
      Base_11.mirror = true;
      setRotation(Base_11, 0F, 0F, 0F);
      Base_12 = new ModelRenderer(this, 0, 0);
      Base_12.addBox(0F, 0F, 0F, 6, 2, 3);
      Base_12.setRotationPoint(2F, 17.5F, -6.5F);
      Base_12.setTextureSize(64, 32);
      Base_12.mirror = true;
      setRotation(Base_12, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Top_1.render(f5);
    Top_2.render(f5);
    Base_1.render(f5);
    Base_2.render(f5);
    Base_3.render(f5);
    Base_4.render(f5);
    Base_5.render(f5);
    Base_6.render(f5);
    Base_7.render(f5);
    Base_8.render(f5);
    Base_11.render(f5);
    Base_12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
